version: "3"

services:
  spring-db:
    container_name: 'spring-db'
    image: 'mysql:latest'
    volumes:
      - /data/spring-db
    ports:
      - "3306:3306"
    networks:
      - spring-net
    environment:
      - MYSQL_USER=app-server
      - MYSQL_ROOT_PASSWORD=sjsjke959Fskl@#43
      - MYSQL_PASSWORD=mEiodjhs154Sk
      - MYSQL_DATABASE=spring-db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  spring-back:
    container_name: 'spring-back'
    image: 'spring-back:latest'
    volumes:
      - /data/spring-back
    networks:
      - spring-net
    ports:
      - "8080:8080"
    depends_on:
      spring-db:
         condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:mysql://spring-db:3306/spring-db?allowPublicKeyRetrieval=true
  
networks:
  spring-net: